use_frameworks!

platform :ios, '10.0'

target 'HTSkinBundle_Example' do
  pod 'HTSkinBundle', :path => '../'
#  pod 'HTSkinBundleResource', :path => '../../HTSkinBundleResource' #资源集成

  target 'HTSkinBundle_Tests' do
    inherit! :search_paths

    
  end
  
  post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "10.0"
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end
end
